name = "remembory-share"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for storing share payloads
# After running `wrangler kv namespace create SHARES`, paste the id below
[[kv_namespaces]]
binding = "SHARES"
id = "24f7cd3fa472486dbbf4283831d8790c"
